### Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

### Load Dataset

In [9]:
df = pd.read_csv("hotel_reviews.csv")

### Dataset Overview

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 80122 entries, 0 to 80121
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   offering_id    80122 non-null  int64
 1   user_id        80122 non-null  str
 2   overall        80122 non-null  float64
 3   value          72861 non-null  float64
 4   service        72494 non-null  float64
 5   location       64545 non-null  float64
 6   rooms          67724 non-null  float64
 7   cleanliness    72979 non-null  float64
 8   sleep_quality  45586 non-null  float64
 9   review_text    80122 non-null  str
dtypes: float64(7), int64(1), str(2)
memory usage: 86.6 MB

### Initial Data Inspection

In [11]:
print("=== Dataset Shape ===")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

print("\n=== Column Names ===")
print(df.columns.tolist())

print("\n=== Data Types ===")
print(df.dtypes)

print("\n=== Missing Values ===")
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])

print("\n=== First Five Records ===")
display(df.head())

=== Dataset Shape ===
Rows: 80,122
Columns: 10

=== Column Names ===
['offering_id', 'user_id', 'overall', 'value', 'service', 'location', 'rooms', 'cleanliness', 'sleep_quality', 'review_text']

=== Data Types ===
offering_id        int64
user_id              str
overall          float64
value            float64
service          float64
location         float64
rooms            float64
cleanliness      float64
sleep_quality    float64
review_text          str
dtype: object

=== Missing Values ===
value             7261
service           7628
location         15577
rooms            12398
cleanliness       7143
sleep_quality    34536
dtype: int64

=== First Five Records ===

,offering_id,user_id,overall,value,service,location,rooms,cleanliness,sleep_quality,review_text
0,1762573,FB1032DECE1162CB3556D05F278AAFFD,4.0,4.0,4.0,5.0,4.0,5.0,4.0,“Great Stay” This is a great property in Midto...
1,1762573,BA524A238B1171206691A6CC3F28F266,4.0,3.0,4.0,5.0,5.0,5.0,5.0,“Its the best of the Andaz Brand in the US.......
2,1456560,EC6CB11E9DC8761710DDA3CF48DD995F,4.0,4.0,4.0,5.0,4.0,5.0,5.0,“A Nice Stay for NYC!” This hotel is a nice st...
3,1762573,C81AB7D49D98FA410EA191E15F427BEC,4.0,5.0,4.0,5.0,5.0,5.0,5.0,“Stunningly Wonderful!” Other hotels in NYC th...
4,1456560,2404E3630B78BB9E8D6583076FBA0742,4.0,4.0,4.0,4.0,4.0,4.0,5.0,"“Modern, minimalist, central hotel” We got a r..."

###  Data Quality

In [12]:
print("=== Duplicate Records ===")
print(df.duplicated().sum())

print("\n=== Missing Value Summary ===")
missing_summary = pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percent": (df.isnull().mean() * 100).round(2)
})

display(missing_summary[missing_summary["Missing Count"] > 0]
        .sort_values("Missing Count", ascending=False))

=== Duplicate Records ===
0

=== Missing Value Summary ===

               Missing Count  Missing Percent
sleep_quality          34536            43.10
location               15577            19.44
rooms                  12398            15.47
service                 7628             9.52
value                   7261             9.06
cleanliness             7143             8.92

### Summary Stats

In [13]:
print("=== Numerical Variable Summary ===")
display(df.describe())

print("\n=== Categorical Variable Summary ===")
display(df.describe(include='object'))

=== Numerical Variable Summary ===

,offering_id,overall,value,service,location,rooms,cleanliness,sleep_quality
count,8.012200e+04,80122.000000,72861.000000,72494.000000,64545.000000,67724.000000,72979.000000,45586.000000
mean,3.090273e+05,3.906280,3.842769,4.052004,4.319606,3.906134,4.225325,4.068925
std,4.302004e+05,0.984847,1.056052,1.054839,0.885012,1.039979,0.958001,1.025927
min,7.257200e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,8.960000e+04,3.000000,3.000000,3.000000,4.000000,3.000000,4.000000,4.000000
50%,1.114220e+05,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000
75%,2.519630e+05,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000
max,3.523356e+06,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

=== Categorical Variable Summary ===

/var/folders/wz/29tjx61923s_d1p75gmh2qfw0000gn/T/ipykernel_67814/3100134254.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

       user_id                                        review_text
count    80122                                              80122
unique   11398                                              80121
top     CATID_  “hotel” its a great experience, rates are fine...
freq       258                                                  2

### Determine Target Variable

In [8]:
print(df.columns.tolist())

['offering_id', 'user_id', 'overall', 'value', 'service', 'location', 'rooms', 'cleanliness', 'sleep_quality', 'review_text']